spring:
  application:
    name: notebookservice
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://mysql/notebookservice?useSSL=false
    platform: mysql
    initialization-mode: always
logging:
  level:
    root: info